name: Advanced Package Tracker (PL)
slug: package_tracker_pl
version: "0.1.1"
description: >
  Tracks DHL (Poland) and InPost packages via scraping/API. Web UI to add/remove
  packages, MQTT Discovery sensors (detailed & summary) + today's delivery counters.
url: https://example.com/advanced-package-tracker
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
homeassistant_api: false
host_network: false
ingress: true
ingress_port: 8099
panel_icon: mdi:package-variant-closed
map:
  - config:rw
  - share:rw
  - addons:rw
  - ssl:ro
options:
  poll_interval_minutes: 7
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  mqtt_base_topic: "package_tracker"
schema:
  poll_interval_minutes: int
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: password
  mqtt_base_topic: str
